steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/playground-s-11-6ade565e/my-node-app', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/playground-s-11-6ade565e/my-node-app']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'my-node-app',
           '--image', 'gcr.io/playground-s-11-6ade565e/my-node-app',
           '--platform', 'managed',
           '--region', 'us-central1',
           '--allow-unauthenticated']

images:
  - 'gcr.io/playground-s-11-6ade565e/my-node-app'

options:
  logging: CLOUD_LOGGING_ONLY

